---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault-issuer
  namespace: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-issuer-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: vault-issuer
type: kubernetes.io/service-account-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/vault-issuer
    server: https://ha-vault.ha-vault:8200
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGZ1RDQ0JHbWdBd0lCQWdJUkFJeWtVakQ1
      V3VPNXdTcngzcG1PQ1Jrd0RRWUpLb1pJaHZjTkFRRUxCUUF3DQpRREVWTUJNR0ExVUVDaE1NUW1G
      dWVtRnBJRU5zYjNWa01TY3dKUVlEVlFRREV4NUNZVzU2WVdrZ1EyeHZkV1FnDQpSMlZ1WlhKaGRH
      VmtJRkp2YjNRZ1EwRXdIaGNOTWpJeE1qRXpNakl4TlRVNVdoY05Nak14TWpFek1qSXhOVFU1DQpX
      akJFTVJVd0V3WURWUVFLRXd4Q1lXNTZZV2tnUTJ4dmRXUXhLekFwQmdOVkJBTVRJa0poYm5waGFT
      QkRiRzkxDQpaQ0JIWlc1bGNtRjBaV1FnVTJWeWRtVnlJRU5sY25Rd2dnRWlNQTBHQ1NxR1NJYjNE
      UUVCQVFVQUE0SUJEd0F3DQpnZ0VLQW9JQkFRRFN5b01zaERDMHoySDYrbnpsWDB0MWVCNVVhM2NY
      K2ZsS2kwRC83UDZzeEV3Q3dIUnYva2I2DQptZDJ1dW1hWU14RjdoQW1YWTFNTlRtRkEvVkVkMXNP
      OFhGWU43eU4vbG1LeTFjNTlpOXpUbHhITlM3WVh2amZjDQpEME5iWlEzTzdWa0dDTzVLNEVibmVt
      UFE1TzJydVdYTDJnV0c1M2Jya1BHV2NIUVAvVjI4TE1jQXpZZ1JvUUt4DQpNRitKMUE2SzAzbG1t
      VDZSVW01WGM5NDJOeUVNT2g2RVRPYzhNVjdnUjR4dW9xbjMvOUZWT2xWb3QzNVVqMmdtDQpsSEFF
      YmJGcUJVUVV5aCs3QzZyNWpFTjRTd0VRL09rb1RkUlJqbFVzK3RyVHhKU0tobVRFUnp6ZHFtOWRj
      Vlg0DQpsM01Vcy9DYUo0cDNlcTFxeUhzMlh4bW41UGxGZncrM0FnTUJBQUdqZ2dKd01JSUNiREFP
      QmdOVkhROEJBZjhFDQpCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEQVlEVlIw
      VEFRSC9CQUl3QURDQ0FqVUdBMVVkDQpFUVNDQWl3d2dnSW9nZ3h3YzJWMVpHOHRkbUYxYkhTQ0dY
      QnpaWFZrYnkxMllYVnNkQzV3YzJWMVpHOHRkbUYxDQpiSFNDSzNCelpYVmtieTEyWVhWc2RDNXdj
      MlYxWkc4dGRtRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lDDQpEbkJ6WlhWa2J5MTJZWFZz
      ZEMwd2dodHdjMlYxWkc4dGRtRjFiSFF0TUM1d2MyVjFaRzh0ZG1GMWJIU0NMWEJ6DQpaWFZrYnkx
      MllYVnNkQzB3TG5CelpYVmtieTEyWVhWc2RDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJJSU9jSE5s
      DQpkV1J2TFhaaGRXeDBMVEdDRzNCelpYVmtieTEyWVhWc2RDMHhMbkJ6WlhWa2J5MTJZWFZzZElJ
      dGNITmxkV1J2DQpMWFpoZFd4MExURXVjSE5sZFdSdkxYWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeUxt
      eHZZMkZzZ2c1d2MyVjFaRzh0DQpkbUYxYkhRdE1vSWJjSE5sZFdSdkxYWmhkV3gwTFRJdWNITmxk
      V1J2TFhaaGRXeDBnaTF3YzJWMVpHOHRkbUYxDQpiSFF0TWk1d2MyVjFaRzh0ZG1GMWJIUXVjM1pq
      TG1Oc2RYTjBaWEl1Ykc5allXeUNEbkJ6WlhWa2J5MTJZWFZzDQpkQzB6Z2h0d2MyVjFaRzh0ZG1G
      MWJIUXRNeTV3YzJWMVpHOHRkbUYxYkhTQ0xYQnpaWFZrYnkxMllYVnNkQzB6DQpMbkJ6WlhWa2J5
      MTJZWFZzZEM1emRtTXVZMngxYzNSbGNpNXNiMk5oYklJT2NITmxkV1J2TFhaaGRXeDBMVFNDDQpH
      M0J6WlhWa2J5MTJZWFZzZEMwMExuQnpaWFZrYnkxMllYVnNkSUl0Y0hObGRXUnZMWFpoZFd4MExU
      UXVjSE5sDQpkV1J2TFhaaGRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNod1IvQUFBQk1BMEdD
      U3FHU0liM0RRRUJDd1VBDQpBNElCQVFCcFpNdVp6cHlOMGFnVUJkMFVHZDZ1Z29oNk9YWnpsTFJ4
      UWkrRDExc0RTMTNvQ3ZCUDcyU3dKaFEzDQpwWGFRczFXTXdyaWNNUFFmaW5FZkdQMlBxWDVIa3g1
      UXFtOGx3Qmk2cVlIMWVpSWhIcmltTjVTSXQ3WGM5R1RpDQpXblY5QVVuakVBczV5Y1V5VDZlT0hR
      eE9mNGs0VDlUalQ5bkFSUVg4ZW1wYnkwUDhmemw4THpFbmZNOTIxNnRBDQpYYnBIUXlzU1VXem5p
      Q2l1REljdncwaVgvMU43L3JhN01mbVlvSUpKVlBRaXZ1TzQwZDNwUk1JMXVxd3BRbFV0DQpJRHRP
      dFl0QnR0M0hoNGI5Vi9BckI0RDVQTmMwajBwQVZJWGt0T3NSTGs2alhuNnlndDlHUEc4U2Y0bUdX
      ZWxaDQorZjNzKzE2RVFGSTZPTjBCQkJ1bWZOYmJTWVB4DQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tDQotLS0tLUJFR0lOIFJTQSBQUklWQVRFIEtFWS0tLS0tDQpNSUlFcFFJQkFBS0NBUUVBMHNx
      RExJUXd0TTloK3ZwODVWOUxkWGdlVkd0M0YvbjVTb3RBLyt6K3JNUk1Bc0IwDQpiLzVHK3BuZHJy
      cG1tRE1SZTRRSmwyTlREVTVoUVAxUkhkYkR2RnhXRGU4amY1WmlzdFhPZll2YzA1Y1J6VXUyDQpG
      NzQzM0E5RFcyVU56dTFaQmdqdVN1Qkc1M3BqME9UdHE3bGx5OW9GaHVkMjY1RHhsbkIwRC8xZHZD
      ekhBTTJJDQpFYUVDc1RCZmlkUU9pdE41WnBrK2tWSnVWM1BlTmpjaEREb2VoRXpuUERGZTRFZU1i
      cUtwOS8vUlZUcFZhTGQrDQpWSTlvSnBSd0JHMnhhZ1ZFRk1vZnV3dXErWXhEZUVzQkVQenBLRTNV
      VVk1VkxQcmEwOFNVaW9aa3hFYzgzYXB2DQpYWEZWK0pkekZMUHdtaWVLZDNxdGFzaDdObDhacCtU
      NVJYOFB0d0lEQVFBQkFvSUJBRWt1bCtYL3F1MUxScWdkDQpDUG1WWVJ4U2JLMUFkaU56M1BIZGNO
      NnBpQzJ4SlBhYm5KRTVSYWxCZkM1cWRxNEdwTjR1RkNwa0NIU0pMc2lpDQphZVFqS09lZll4MEpW
      bGk0ZkdHOFN5bFpRbnlQYVZYT0lGVVQ3RTdSV2NCRVVFdjBLVUVvSHBzT1RHK1hGVXAwDQpBSFBy
      TlFWV0Z5OGo4eXlMc09SYS9HQ0V4V05Md3czT3gyc1BvKzVXZkZ0M05VSlJjOFVad3dqVFFVYTJs
      VisrDQoyYmlPMXp1amltcy9EeXBMcVMvUE14TVR4NTJJYTI4ek5QcDlZZ2VuV3NhWXZ1cVVxZCsy
      aDF2bklWYVpSZnA5DQpVcUN1V0VVQjFpTTBtYjZKV2l3M0oyYjFXNmFCb2I5ZFN3Yjg5VFY4NHZm
      WDJoZk5ncnQvcVFmaDA5dnJWN1c4DQpJd3BVYkprQ2dZRUE4U0lPWkNZQ2t3ZzVtWXYwbUJwbG1z
      c2xnaTRGRG54U0F4aHRldUlxM0RoMkI2c2xEUmlxDQpsL09CL3I0ZVV0WDBjVmJlbi9nTlV5ZzQr
      MkJzdFloWFdscU4waGJkanJUTGZBRm5taGl6dXIzQ0ZaQTNnQXJuDQp5YnlBZlJwWkprcXdTWGhS
      SWZiWHp1U1RSMUtRWU5ES1FwQ2V2dXd0a0RLWDNhRnM3Uy9UcHkwQ2dZRUEzOG1ODQpGNWMrdU1W
      ZVk4VEo5QTI1bjVKSm52S3ZZZy9FYWNkWGVpMnkzYTZiQVRMeXpBVk9SUDFlTGtuNHhzV1NEUkxY
      DQpYc09pRmdSY2NOODhZb01NdU9kdFp5cGtGSHhaazNtWXNValB2RmpRRE1oQy9HTWcwYThDRXMw
      bzdZNnhuK2xjDQpCVStPcXYrYS9TNWd5ckRhTXBkLzRRc09aMlo3dXo0UUtyU1E0UE1DZ1lFQXN3
      ZUlDODgweGhtck9sZHhDS1ZBDQpuc2NKV0RmMnhTU0VkNHZoYlFVU3NXS3lMMHRnUFBMOVpjZ0Qw
      akV4cm1yd0RGNWs5L3hoV0VaYTJEaGxQZnEyDQpjSDBmSXNhYlJPTHkyV1RwbUwyU1k2bVR1aExU
      UWh2V3NDOW1ibnZyaU1TWFVsVWtWOFUvd1hwdjV0cGtHNTJwDQpMZmJXQmdhd1pZbEt1K0NvVVFu
      YmFSa0NnWUVBbmNxOXczNlBhVFV4WXVPbENvS0srZXJxSWpzNFVzcVBVWTZQDQpMY1QvTTdRajgy
      cDdMRVFwZGhlNHlxYTUxVjRGcDFZN3FjUURpOGF6YjVyWU54WDBhSVExN2VKRUF2WFRLMXMzDQp3
      UGw0RUhRRzdweGVMeHV1VG1zNTZRdmo2ZTBOYlpYYm5wc0VHNnB6SEVZUlZabnhvRzZXYXBXaktH
      Rm9xUlFQDQp6aXpYWXVVQ2dZRUFsS2pLdW1PdnNFa0gzOGh0b0lGYjMyMDV4ejNzWGJCSElyVXBp
      YUJSS21XMGNPZ2pIUjdRDQppMTFDbnVXMzJ4Wm4wRjJDczlhY3NvdGNUci9jU2IvWXpjZ003WTJ5
      aGRtazdSVnJxSmJ0UWNueEdWbVZMNnVuDQpFN3l1Z2MvbDQzZXp2THJMU255WGh1cW5CLzIyS1h2
      c0FObHZMOTZjRHYzUlhnSUpsbEFGbkdjPQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0N
      Cg==
    auth:
      kubernetes:
        role: vault-issuer
        mountPath: /v1/auth/vault-issuer/kubernetes
        secretRef:
          name: vault-issuer-token
          key: token